[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "godot-mod-overhaul-system"
version = "1.0"
description = "External mod loader and patcher for Godot games."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Kim", email = "kimmy130507@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/kimmy130507/godot-mod-overhaul-system"
"Repository" = "https://github.com/kimmy130507/godot-mod-overhaul-system"

[project.scripts]
godot-mod-overhaul-system = "gmos:main"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
  ".git",
  "__pycache__",
  ".venv",
  "venv",
  "build",
  "dist",
  ".eggs",
  ".github",
]